server:
  port: 8070
spring:
  application:
    name: log-ingester
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  cloud:
    stream:
      default-binder: rabbit
      bindings:
        log-in-0:
          destination: log-ingester

---
spring.config.activate.on-profile: cloud
spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.amqp.RabbitAutoConfiguration
  cloud:
    stream:
      default-binder: servicebus
