server:
  port: 8080
spring:
  application:
    name: payment-gateway
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  cloud:
    stream:
      default-binder: rabbit
      bindings:
        log-out-0:
          destination: log-ingester
credit-service:
  root-uri: http://localhost:8081

---
spring.config.activate.on-profile: cloud
spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.amqp.RabbitAutoConfiguration
  cloud:
    stream:
      default-binder: servicebus
      servicebus:
        bindings:
          log-out-0:
            producer:
              entity-type: queue
credit-service:
  root-uri: https://dev-pf-asc-credit-service.azuremicroservices.io
